import { bn, BN_ZERO, BN_HUNDRED } from "@/lib/config"
import { normalizeToUsd } from "@/lib/pnl/currency"
import type { Snapshot, Transaction, ExchangeRate } from "@/types/database"
import type { AssetPnL } from "@/lib/pnl/types"

export type TimeRange =
  | "1D"
  | "1W"
  | "1M"
  | "3M"
  | "6M"
  | "YTD"
  | "1Y"
  | "ALL"

export interface PnLPoint {
  date: string
  totalUsd: number
  investedUsd: number
  pnlUsd: number
}

export interface MonthlyReturn {
  month: string // "2026-03"
  label: string // "Mar 2026"
  returnPct: number
  returnUsd: number
}

export interface PerformanceMetrics {
  monthlyReturns: MonthlyReturn[]
  ytdReturnPct: number | null
  allTimeReturnPct: number | null
  cagr: number | null
  maxDrawdownPct: number
  bestMonth: MonthlyReturn | null
  worstMonth: MonthlyReturn | null
  drawdownSeries: { date: string; drawdownPct: number }[]
}

const monthLabels = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
]

function formatMonthLabel(dateStr: string): string {
  const d = new Date(dateStr)
  return `${monthLabels[d.getMonth()]} ${d.getFullYear()}`
}

function pad2(n: number): string {
  return n.toString().padStart(2, "0")
}

/** Local-date "YYYY-MM-DD" string (avoids timezone drift from toISOString). */
function localIso(d: Date): string {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`
}

export function filterByTimeRange(
  snapshots: Snapshot[],
  range: TimeRange,
): Snapshot[] {
  if (range === "ALL" || snapshots.length === 0) return snapshots

  const now = new Date()
  let cutoff: Date

  switch (range) {
    case "1D":
      cutoff = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1)
      break
    case "1W":
      cutoff = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7)
      break
    case "1M":
      cutoff = new Date(now.getFullYear(), now.getMonth() - 1, now.getDate())
      break
    case "3M":
      cutoff = new Date(now.getFullYear(), now.getMonth() - 3, now.getDate())
      break
    case "6M":
      cutoff = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate())
      break
    case "YTD":
      cutoff = new Date(now.getFullYear(), 0, 1)
      break
    case "1Y":
      cutoff = new Date(now.getFullYear() - 1, now.getMonth(), now.getDate())
      break
  }

  const cutoffStr = localIso(cutoff)
  const inRange = snapshots.filter((s) => s.snapshot_date >= cutoffStr)

  // For ranges of 1 month or longer, include the latest snapshot strictly
  // before the cutoff as a "start anchor". This keeps the chart populated
  // when snapshot granularity is monthly (e.g. monthly snapshots and a "1M"
  // window where the closest snapshot is just outside the window). We do
  // NOT do this for 1D / 1W because extending those back to a month-ago
  // snapshot would misrepresent the requested range.
  const supportsAnchor =
    range === "1M" ||
    range === "3M" ||
    range === "6M" ||
    range === "YTD" ||
    range === "1Y"

  if (supportsAnchor) {
    let anchorIdx = -1
    for (let i = 0; i < snapshots.length; i++) {
      if (snapshots[i].snapshot_date < cutoffStr) {
        anchorIdx = i
      } else {
        break
      }
    }
    if (anchorIdx >= 0) {
      return [snapshots[anchorIdx], ...inRange]
    }
    // No real snapshot before cutoff (user joined the platform inside this
    // window). Synthesize a zero-value anchor at the cutoff so the chart
    // visually starts at the requested window edge with P&L = $0, instead
    // of jumping in only at the first transaction date.
    const syntheticAnchor: Snapshot = {
      id: `__synthetic_${cutoffStr}`,
      user_id: snapshots[0]?.user_id ?? "",
      snapshot_date: cutoffStr,
      total_usd: 0,
      total_try: 0,
      breakdown: null,
      created_at: cutoffStr,
    }
    return [syntheticAnchor, ...inRange]
  }

  return inRange
}

/**
 * External cash flow signed value for Modified Dietz.
 *
 * "External" means money the investor put in or took out — not income or
 * expenses generated by the holdings themselves. Buys / sells / transfers
 * are external; dividends, interest and standalone fees are internal and
 * should not skew the period return.
 *
 * Sign convention: positive = inflow into the portfolio (capital deployed).
 */
function externalCashFlowUsd(
  tx: Transaction,
  rates: ExchangeRate[],
): number {
  const totalUsd = normalizeToUsd(
    tx.total_cost ?? 0,
    tx.price_currency,
    tx.date,
    rates,
  ).toNumber()
  const feeUsd = tx.fee
    ? normalizeToUsd(
        tx.fee,
        tx.fee_currency ?? tx.price_currency,
        tx.date,
        rates,
      ).toNumber()
    : 0
  switch (tx.type) {
    case "buy":
      return totalUsd + feeUsd
    case "sell":
      return -(totalUsd - feeUsd)
    case "transfer_in":
      return totalUsd
    case "transfer_out":
      return -totalUsd
    default:
      // dividend / interest / fee → internal, no external cash flow
      return 0
  }
}

/**
 * Modified Dietz monthly returns.
 *
 * R = (V_end − V_start − C) / (V_start + Σ C_i · w_i),  w_i = (T − t_i) / T
 *
 * Without daily granularity, "monthly" here means "between consecutive
 * snapshots". Cash flows that happened inside the period are weighted by
 * the time they were exposed to market movement, so depositing $1k mid-period
 * doesn't masquerade as +X% return.
 */
export function computeMonthlyReturns(
  snapshots: Snapshot[],
  transactions: Transaction[] = [],
  rates: ExchangeRate[] = [],
): MonthlyReturn[] {
  const returns: MonthlyReturn[] = []
  const sortedTxs = [...transactions].sort((a, b) =>
    a.date < b.date ? -1 : a.date > b.date ? 1 : 0,
  )

  const MS_PER_DAY = 24 * 60 * 60 * 1000

  for (let i = 1; i < snapshots.length; i++) {
    const prevSnap = snapshots[i - 1]
    const currSnap = snapshots[i]
    const vStart = bn(prevSnap.total_usd)
    const vEnd = bn(currSnap.total_usd)

    const periodStart = new Date(`${prevSnap.snapshot_date}T00:00:00Z`)
    const periodEnd = new Date(`${currSnap.snapshot_date}T00:00:00Z`)
    const totalDays = Math.max(
      1,
      (periodEnd.getTime() - periodStart.getTime()) / MS_PER_DAY,
    )

    let netCashFlow = 0
    let weightedCashFlow = 0
    for (const tx of sortedTxs) {
      const txDate = new Date(`${tx.date.slice(0, 10)}T00:00:00Z`).getTime()
      if (txDate <= periodStart.getTime() || txDate > periodEnd.getTime()) continue
      const c = externalCashFlowUsd(tx, rates)
      if (c === 0) continue
      const t = (txDate - periodStart.getTime()) / MS_PER_DAY
      const w = (totalDays - t) / totalDays
      netCashFlow += c
      weightedCashFlow += c * w
    }

    const denom = vStart.plus(bn(weightedCashFlow))
    if (denom.isLessThanOrEqualTo(0)) continue

    const numer = vEnd.minus(vStart).minus(bn(netCashFlow))
    const returnPct = numer.div(denom).times(BN_HUNDRED).toNumber()
    const returnUsd = numer.toNumber()

    returns.push({
      month: currSnap.snapshot_date.slice(0, 7),
      label: formatMonthLabel(currSnap.snapshot_date),
      returnPct,
      returnUsd,
    })
  }

  return returns
}

export function computeYTDReturn(snapshots: Snapshot[]): number | null {
  if (snapshots.length < 2) return null

  const year = new Date().getFullYear()
  const janSnapshot = snapshots.find(
    (s) => s.snapshot_date.startsWith(`${year}-01`),
  )
  const latest = snapshots[snapshots.length - 1]

  if (!janSnapshot || !latest) return null

  const start = bn(janSnapshot.total_usd)
  if (start.isZero()) return null

  return bn(latest.total_usd).minus(start).div(start).times(BN_HUNDRED).toNumber()
}

/**
 * All-time return = total P&L / total invested capital. Anchors on the user's
 * actual money in (not the first snapshot we happened to take).
 */
export function computeAllTimeReturn(
  totalPnlUsd: number,
  totalInvestedUsd: number,
): number | null {
  const investedAbs = Math.abs(totalInvestedUsd)
  if (investedAbs === 0) return null
  return (totalPnlUsd / investedAbs) * 100
}

/**
 * CAGR anchored on the user's first transaction (not first snapshot).
 *
 * For simple deposits with no withdrawals this is a fair approximation. With
 * irregular cash flows the rigorous metric is XIRR (money-weighted return);
 * we keep CAGR as a friendly summary and note the tradeoff.
 */
export function computeCAGR(
  currentValueUsd: number,
  totalInvestedUsd: number,
  firstTransactionDate: string | null,
): number | null {
  if (!firstTransactionDate) return null
  if (totalInvestedUsd <= 0 || currentValueUsd <= 0) return null

  const startDate = new Date(firstTransactionDate)
  const endDate = new Date()
  const years =
    (endDate.getTime() - startDate.getTime()) / (365.25 * 24 * 60 * 60 * 1000)
  if (years < 0.08) return null // Less than ~1 month

  const ratio = currentValueUsd / totalInvestedUsd
  return (Math.pow(ratio, 1 / years) - 1) * 100
}

export function computeDrawdown(
  snapshots: Snapshot[],
): { date: string; drawdownPct: number }[] {
  const series: { date: string; drawdownPct: number }[] = []
  let peak = BN_ZERO

  for (const snap of snapshots) {
    const val = bn(snap.total_usd)
    if (val.isGreaterThan(peak)) peak = val

    const drawdownPct = peak.isGreaterThan(0)
      ? val.minus(peak).div(peak).times(BN_HUNDRED).toNumber()
      : 0
    series.push({ date: snap.snapshot_date, drawdownPct })
  }

  return series
}

export interface CategoryAttributionRow {
  category: string
  costBasisUsd: number
  valueUsd: number
  pnlUsd: number
  /** Share of total portfolio P&L attributable to this category. */
  contributionPct: number
}

/**
 * Per-category attribution computed from FIFO cost basis (not snapshots).
 *
 * "Cost Basis" = what you actually invested in that category (fee-inclusive).
 * "Value" = current market value. "P&L" = Value − Cost Basis. "Contribution"
 * = this category's share of total portfolio P&L.
 *
 * Anchored on real transactions, so it doesn't lie about the starting point
 * when snapshots happen to begin after the first deposit.
 */
export function computeCategoryAttribution(
  assetPnLs: AssetPnL[],
): CategoryAttributionRow[] {
  if (assetPnLs.length === 0) return []

  type Bucket = {
    costBasis: ReturnType<typeof bn>
    value: ReturnType<typeof bn>
    pnl: ReturnType<typeof bn>
  }
  const buckets = new Map<string, Bucket>()
  let totalPnl = BN_ZERO

  for (const a of assetPnLs) {
    if (a.category === "fiat") continue // fiat has no meaningful P&L

    const existing = buckets.get(a.category) ?? {
      costBasis: BN_ZERO,
      value: BN_ZERO,
      pnl: BN_ZERO,
    }
    existing.costBasis = existing.costBasis.plus(a.costBasisUsd)
    existing.value = existing.value.plus(a.currentValueUsd)
    const assetPnl = a.unrealizedPnlUsd.plus(a.realizedPnlUsd)
    existing.pnl = existing.pnl.plus(assetPnl)
    totalPnl = totalPnl.plus(assetPnl)
    buckets.set(a.category, existing)
  }

  const totalPnlAbs = totalPnl.abs()
  const rows: CategoryAttributionRow[] = []
  for (const [category, b] of buckets) {
    const contributionPct = totalPnlAbs.isZero()
      ? 0
      : b.pnl.div(totalPnlAbs).times(BN_HUNDRED).toNumber()
    rows.push({
      category,
      costBasisUsd: b.costBasis.toNumber(),
      valueUsd: b.value.toNumber(),
      pnlUsd: b.pnl.toNumber(),
      contributionPct,
    })
  }
  return rows.sort((a, b) => Math.abs(b.pnlUsd) - Math.abs(a.pnlUsd))
}

export interface PerformanceMetricsInput {
  snapshots: Snapshot[]
  transactions: Transaction[]
  rates: ExchangeRate[]
  totalInvestedUsd: number
  totalPnlUsd: number
  currentValueUsd: number
}

export function computePerformanceMetrics(
  input: PerformanceMetricsInput,
): PerformanceMetrics {
  const {
    snapshots,
    transactions,
    rates,
    totalInvestedUsd,
    totalPnlUsd,
    currentValueUsd,
  } = input

  const monthlyReturns = computeMonthlyReturns(snapshots, transactions, rates)
  const ytdReturnPct = computeYTDReturn(snapshots)
  const allTimeReturnPct = computeAllTimeReturn(totalPnlUsd, totalInvestedUsd)
  const firstTxDate = transactions.length > 0
    ? transactions
        .map((t) => t.date.slice(0, 10))
        .reduce((min, d) => (d < min ? d : min))
    : null
  const cagr = computeCAGR(currentValueUsd, totalInvestedUsd, firstTxDate)
  const drawdownSeries = computeDrawdown(snapshots)
  const maxDrawdownPct =
    drawdownSeries.length > 0
      ? Math.min(...drawdownSeries.map((d) => d.drawdownPct))
      : 0

  const bestMonth =
    monthlyReturns.length > 0
      ? monthlyReturns.reduce((a, b) =>
          a.returnPct > b.returnPct ? a : b,
        )
      : null

  const worstMonth =
    monthlyReturns.length > 0
      ? monthlyReturns.reduce((a, b) =>
          a.returnPct < b.returnPct ? a : b,
        )
      : null

  return {
    monthlyReturns,
    ytdReturnPct,
    allTimeReturnPct,
    cagr,
    maxDrawdownPct,
    bestMonth,
    worstMonth,
    drawdownSeries,
  }
}

/**
 * Apply a single transaction's impact on cumulative net invested capital (USD).
 *
 * Convention used here:
 *   buy            -> +total + fee   (real cash deployed for an asset)
 *   sell           -> -total + fee   (cash returned, fee still consumed)
 *   transfer_in    -> +total         (cost basis carried in — opening
 *                                     balance or platform-to-platform move)
 *   transfer_out   -> -total         (cost basis carried out — symmetric)
 *   dividend       -> -total         (cash returned to the account)
 *   interest       -> -total         (cash returned to the account)
 *   fee            -> +fee || +total (standalone fee — pure cost)
 *
 * For genuine platform-to-platform transfers (a transfer_out paired with a
 * transfer_in of equal cost basis), the two cancel and the net invested
 * stays unchanged. For "loading event" / opening-balance entries (a lone
 * transfer_in with no matching out), the cost basis recorded on the
 * transaction is added to invested capital — so the asset doesn't appear
 * to be "free" relative to its current value.
 */
function applyTxToInvested(
  tx: Transaction,
  rates: ExchangeRate[],
  cum: ReturnType<typeof bn>,
): ReturnType<typeof bn> {
  const totalUsd = normalizeToUsd(
    tx.total_cost ?? 0,
    tx.price_currency,
    tx.date,
    rates,
  )
  const feeUsd = tx.fee
    ? normalizeToUsd(tx.fee, tx.fee_currency ?? tx.price_currency, tx.date, rates)
    : bn(0)

  switch (tx.type) {
    case "buy":
      return cum.plus(totalUsd).plus(feeUsd)
    case "sell":
      return cum.minus(totalUsd).plus(feeUsd)
    case "transfer_in":
      return cum.plus(totalUsd)
    case "transfer_out":
      return cum.minus(totalUsd)
    case "dividend":
    case "interest":
      return cum.minus(totalUsd)
    case "fee":
      return cum.plus(feeUsd.isZero() ? totalUsd : feeUsd)
    default:
      return cum
  }
}

/**
 * Compute a P&L time series from snapshots and transactions.
 *
 * P&L at time T is defined as `total_value(T) - net_invested_capital(T)`.
 * Net invested capital is the cumulative cost basis deployed: buys plus
 * fees minus sells minus dividends/interest received, with `transfer_in`
 * adding and `transfer_out` subtracting the recorded cost basis. Real
 * platform-to-platform transfers cancel out (out + in net to zero);
 * opening-balance entries (lone `transfer_in`s) correctly add their cost
 * basis so the asset isn't treated as zero-cost.
 *
 * Transactions must be sortable by date. Rates are used to normalize
 * non-USD totals to USD.
 */
export function computePnLTimeSeries(
  snapshots: Snapshot[],
  transactions: Transaction[],
  rates: ExchangeRate[],
): PnLPoint[] {
  if (snapshots.length === 0) return []

  const txs = [...transactions].sort((a, b) =>
    a.date < b.date ? -1 : a.date > b.date ? 1 : 0,
  )

  const series: PnLPoint[] = []
  let cumInvested = bn(0)
  let txIdx = 0

  for (const snap of snapshots) {
    const cutoff = snap.snapshot_date

    // tx.date carries a time component (e.g. "2026-05-03 21:00:00+00")
    // while snap.snapshot_date is date-only ("2026-05-03"). String-comparing
    // the two with `<=` excludes same-day deposits because the longer
    // timestamp sorts after the bare date. Slice to YYYY-MM-DD so a deposit
    // recorded on snapshot day counts toward that day's invested capital.
    while (
      txIdx < txs.length &&
      txs[txIdx].date.slice(0, 10) <= cutoff
    ) {
      cumInvested = applyTxToInvested(txs[txIdx], rates, cumInvested)
      txIdx++
    }

    const totalUsd = bn(snap.total_usd ?? 0)
    const pnl = totalUsd.minus(cumInvested)

    series.push({
      date: snap.snapshot_date,
      totalUsd: totalUsd.toNumber(),
      investedUsd: cumInvested.toNumber(),
      pnlUsd: pnl.toNumber(),
    })
  }

  return series
}

/**
 * Compute the current cumulative net invested capital in USD across all
 * transactions (treats all transactions as "applied" through "now"). Used
 * to anchor the live "now" point in the P&L series.
 */
export function computeCurrentInvestedUsd(
  transactions: Transaction[],
  rates: ExchangeRate[],
): number {
  let cum = bn(0)
  for (const tx of transactions) {
    cum = applyTxToInvested(tx, rates, cum)
  }
  return cum.toNumber()
}
